server:
  port: 8081

# DataSource Config
spring:
#  profiles:
#    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/spider?serverTimezone=Asia/Shanghai
    username: root
    password: root
#  redis:
#    host:
#    port: 6379
#    password: root
#    connect-timeout: 10s  # 连接超时时间
#    lettuce: # lettuce redis客户端配置
#      pool: # 连接池配置
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-wait: 200s  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 8 # 连接池中的最大空闲连接 默认 8
#        min-idle: 0 # 连接池中的最小空闲连接 默认 0

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml


knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽  true=屏蔽
  production: false

avatarImagesFilePath: classpath:assets/userAvatar/